package com.amer.inventory.data

import androidx.room.Entity
import androidx.room.PrimaryKey


/**
 * Entity data class represents a single row in the database.
 * @param id The unique identifier for the item. Auto-generated by the database.
 * @param name The name of the item.
 * @param price The price of the item.
 * @param quantity The quantity of the item in stock.
 */
@Entity(tableName = "items")
class Item(
    @PrimaryKey(autoGenerate = true)
    val id: Int,
    val name: String,
    val price: Double,
    val quantity: Int,
)